<?php
$reports = $data['reports'] ?? [];
$stats = $data['stats'] ?? [];
$dateFrom = $data['dateFrom'] ?? date('Y-m-d', strtotime('-30 days'));
$dateTo = $data['dateTo'] ?? date('Y-m-d');
$user_name = $data['user_name'] ?? 'Administrator';
$hotspotIntelligence = $data['hotspot_intelligence'] ?? [];
$trendComparison = $data['trend_comparison'] ?? [];
$decisionSupport = $data['decision_support'] ?? [];
$total = (int)($stats['total'] ?? 0);
$resolved = (int)($stats['resolved'] ?? 0);
$pending = (int)($stats['pending'] ?? 0);
$verified = (int)($stats['verified'] ?? 0);
$inProgress = (int)($stats['in_progress'] ?? 0);
$resolutionRate = $total > 0 ? round(($resolved / $total) * 100) : 0;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analytics Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Arial, sans-serif; background: #fff; color: #1e293b; padding: 40px; max-width: 1200px; margin: 0 auto; }
        @media print { body { padding: 20px; } .no-print { display: none !important; } }
        .header { border-bottom: 3px solid #10B981; padding-bottom: 15px; margin-bottom: 25px; display: flex; justify-content: space-between; align-items: flex-end; }
        .header h1 { font-size: 26px; color: #0f172a; }
        .header .sub { color: #64748b; font-size: 14px; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 15px; margin-bottom: 30px; }
        .stat-box { background: #f8fafc; padding: 15px 20px; border-radius: 8px; border-left: 4px solid #10B981; }
        .stat-box .number { font-size: 24px; font-weight: 700; color: #0f172a; }
        .stat-box .label { font-size: 11px; color: #64748b; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 15px; }
        th { background: #0f172a; color: white; padding: 10px 12px; text-align: left; }
        td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
        tr:nth-child(even) { background: #f8fafc; }
        .filter-info { background: #f1f5f9; padding: 12px 16px; border-radius: 6px; margin-bottom: 20px; font-size: 13px; }
        .section-title { font-size: 16px; font-weight: 700; margin: 25px 0 10px; color: #0f172a; }
        .insight-box { background: #ecfdf5; border: 1px solid #a7f3d0; padding: 12px; border-radius: 8px; margin-bottom: 10px; font-size: 13px; }
        .btn-print { display: inline-block; padding: 10px 30px; background: #10B981; color: white; font-weight: 700; border: none; border-radius: 8px; cursor: pointer; font-size: 14px; margin-top: 20px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 12px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>Statistics &amp; Analytics Report</h1>
            <div class="sub">Barangay Dulong Bayan · <?php echo date('F d, Y'); ?></div>
        </div>
        <div class="sub">Generated by: <?php echo htmlspecialchars($user_name); ?></div>
    </div>

    <div class="filter-info">
        <strong>Period:</strong> <?php echo date('M d, Y', strtotime($dateFrom)); ?> – <?php echo date('M d, Y', strtotime($dateTo)); ?>
        <?php if (!empty($data['category_name'])): ?>
            &nbsp;|&nbsp; <strong>Category:</strong> <?php echo htmlspecialchars($data['category_name']); ?>
        <?php endif; ?>
        <?php if (!empty($data['purok_name'])): ?>
            &nbsp;|&nbsp; <strong>Purok:</strong> <?php echo htmlspecialchars($data['purok_name']); ?>
        <?php endif; ?>
        <?php if (!empty($data['status'])): ?>
            &nbsp;|&nbsp; <strong>Status:</strong> <?php echo htmlspecialchars($data['status']); ?>
        <?php endif; ?>
    </div>

    <div class="stats-grid">
        <div class="stat-box"><div class="number"><?php echo $total; ?></div><div class="label">Total Reports</div></div>
        <div class="stat-box"><div class="number"><?php echo $pending; ?></div><div class="label">Pending</div></div>
        <div class="stat-box"><div class="number"><?php echo $verified; ?></div><div class="label">Verified</div></div>
        <div class="stat-box"><div class="number"><?php echo $inProgress; ?></div><div class="label">In Progress</div></div>
        <div class="stat-box"><div class="number"><?php echo $resolved; ?></div><div class="label">Resolved</div></div>
        <div class="stat-box"><div class="number"><?php echo $resolutionRate; ?>%</div><div class="label">Resolution Rate</div></div>
    </div>

    <div class="section-title">Trend Comparison</div>
    <table>
        <thead><tr><th>Metric</th><th>Current</th><th>Previous</th><th>Change</th></tr></thead>
        <tbody>
            <tr>
                <td>Total Reports</td>
                <td><?php echo $trendComparison['total_reports']['current'] ?? 0; ?></td>
                <td><?php echo $trendComparison['total_reports']['previous'] ?? 0; ?></td>
                <td><?php echo ($trendComparison['total_reports']['change'] ?? 0); ?>%</td>
            </tr>
            <tr>
                <td>Resolution Rate</td>
                <td><?php echo ($trendComparison['resolution_rate']['current'] ?? 0); ?>%</td>
                <td><?php echo ($trendComparison['resolution_rate']['previous'] ?? 0); ?>%</td>
                <td><?php echo ($trendComparison['resolution_rate']['change'] ?? 0); ?>%</td>
            </tr>
        </tbody>
    </table>

    <?php if (!empty($hotspotIntelligence)): ?>
    <div class="section-title">Hotspot Intelligence</div>
    <table>
        <thead><tr><th>Priority</th><th>Purok</th><th>Reports</th><th>Dominant Category</th><th>Latest Report</th></tr></thead>
        <tbody>
            <?php $p = 1; foreach ($hotspotIntelligence as $spot): ?>
            <tr>
                <td><?php echo $p++; ?></td>
                <td><?php echo htmlspecialchars($spot['purok_name']); ?></td>
                <td><?php echo $spot['report_count']; ?></td>
                <td><?php echo htmlspecialchars($spot['dominant_category'] ?? 'N/A'); ?></td>
                <td><?php echo date('M d, Y', strtotime($spot['latest_report'])); ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>

    <?php if (!empty($decisionSupport['highest_hotspot'])): ?>
    <div class="section-title">Decision Support</div>
    <div class="insight-box">
        <strong>Highest-priority hotspot:</strong>
        <?php echo htmlspecialchars($decisionSupport['highest_hotspot']['purok_name']); ?>
        (<?php echo $decisionSupport['highest_hotspot']['report_count']; ?> reports)
    </div>
    <?php endif; ?>

    <div class="section-title">Report List</div>
    <table>
        <thead>
            <tr><th>Report ID</th><th>Date</th><th>Reporter</th><th>Category</th><th>Purok</th><th>Status</th><th>Supports</th></tr>
        </thead>
        <tbody>
            <?php if (!empty($reports)): ?>
                <?php foreach ($reports as $r): ?>
                <tr>
                    <td><?php echo $r['id']; ?></td>
                    <td><?php echo date('M d, Y', strtotime($r['submission_date'])); ?></td>
                    <td><?php echo htmlspecialchars($r['reporter']); ?></td>
                    <td><?php echo htmlspecialchars($r['category'] ?? 'N/A'); ?></td>
                    <td><?php echo htmlspecialchars($r['purok'] ?? 'N/A'); ?></td>
                    <td><?php echo htmlspecialchars($r['status']); ?></td>
                    <td><?php echo (int)($r['support_count'] ?? 0); ?></td>
                </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr><td colspan="7" style="text-align:center;padding:20px;color:#94a3b8;">No reports found.</td></tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">
        For official use only. Generated by <?php echo htmlspecialchars($user_name); ?> on <?php echo date('M d, Y h:i A'); ?>.
    </div>

    <div class="no-print" style="text-align:center;margin-top:30px;">
        <button onclick="window.print()" class="btn-print">Print / Save as PDF</button>
    </div>
</body>
</html>
