<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Waste Report Summary</title>
    <!-- Tailwind CSS (Print specific) -->
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            .no-print { display: none !important; }
            body { background: white; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body class="bg-gray-100 p-8 text-gray-800 font-sans">
    
    <div class="max-w-5xl mx-auto bg-white p-10 shadow-lg rounded-sm border border-gray-200">
        
        <div class="flex justify-between items-center mb-8 border-b pb-4">
            <div>
                <h1 class="text-3xl font-bold uppercase tracking-wider">Waste Report Summary</h1>
                <p class="text-gray-500 mt-1">Barangay Dulong Bayan</p>
            </div>
            <div class="text-right">
                <p class="font-bold">Date Generated: <?php echo date('F d, Y'); ?></p>
                <p class="text-gray-600 font-medium mt-1">Generated By: <?php echo $_SESSION['user_name']; ?></p>
            </div>
        </div>

        <div class="flex justify-between mb-6">
            <div class="w-1/3">
                <h3 class="font-bold text-gray-700 uppercase underline mb-2">Summary Statistics</h3>
                <ul class="text-sm border p-4 bg-gray-50 rounded">
                    <?php 
                            // Make view robust: prefer $data['reports'] but fall back to $reports or empty array
                            $reports_list = [];
                            if (isset($data) && is_array($data) && isset($data['reports']) && is_array($data['reports'])) {
                                $reports_list = $data['reports'];
                            } elseif (isset($reports) && is_array($reports)) {
                                $reports_list = $reports;
                            }

                            $stats = ['total'=>0, 'pending'=>0, 'verified'=>0, 'resolved'=>0];
                            foreach($reports_list as $r) {
                                $stats['total']++;
                                $statusKey = $r['status'] ?? 'pending';
                                if (!isset($stats[$statusKey])) $stats[$statusKey] = 0;
                                $stats[$statusKey]++;
                            }
                        ?>
                    <li>Total Reports: <?php echo $stats['total']; ?></li>
                    <li>Pending: <?php echo $stats['pending']; ?></li>
                    <li>Verified: <?php echo $stats['verified']; ?></li>
                    <li>Resolved: <?php echo $stats['resolved']; ?></li>
                </ul>
            </div>
        </div>

        <table class="w-full text-left text-sm border border-gray-300">
            <thead class="bg-gray-800 text-white">
                <tr>
                    <th class="p-3 border">ID</th>
                    <th class="p-3 border">Date</th>
                    <th class="p-3 border">Reporter</th>
                    <th class="p-3 border w-1/3">Description</th>
                    <th class="p-3 border">Location</th>
                    <th class="p-3 border">Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($reports_list as $r): ?>
                <tr class="border-b even:bg-gray-50">
                    <td class="p-3 border"><?php echo $r['id']; ?></td>
                    <td class="p-3 border"><?php echo date('M d, Y', strtotime($r['submission_date'])); ?></td>
                    <td class="p-3 border"><?php echo htmlspecialchars($r['name']); ?></td>
                    <td class="p-3 border truncate w-1/3 text-xs"><?php echo htmlspecialchars($r['description']); ?></td>
                    <td class="p-3 border text-xs"><?php echo htmlspecialchars($r['location_name'] ?? 'Unknown location'); ?></td>
                    <td class="p-3 border font-bold uppercase"><?php echo $r['status']; ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="mt-12 pt-8 border-t flex justify-between items-center text-sm text-gray-500">
            <p>Certified Correct:</p>
            <div>
                <div class="border-b border-black w-48 mb-2"></div>
                <p class="text-center italic uppercase"><?php echo $_SESSION['user_name']; ?></p>
                <p class="text-center text-xs">Barangay Secretary</p>
            </div>
        </div>
        
    </div>

    <div class="text-center mt-6 no-print space-x-4">
        <button onclick="window.print()" class="bg-blue-600 text-white px-6 py-2 rounded shadow font-bold hover:bg-blue-700">Print as PDF</button>
        <a href="<?php echo app_url('admin/reports'); ?>" class="bg-gray-600 text-white px-6 py-2 rounded shadow font-bold hover:bg-gray-700">Back</a>
    </div>
</body>
</html>
